create table `paises` (
  `id` smallint unsigned not null auto_increment,
  `nome` varchar(255) not null,
  `sigla` char(4) default null,
  primary key (`id`),
  index `paises_nome_idx` (`nome`)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci;


LOCK TABLES `paises` WRITE;

INSERT INTO `paises` VALUES
(4, 'Afeganistão', 'AFG'),
(8, 'Albânia', 'ALB'),
(10, 'Antártida', 'ATA'),
(12, 'Argélia', 'DZA'),
(16, 'Samoa Americana', 'ASM'),
(20, 'Andorra', 'AND'),
(24, 'Angola', 'AGO'),
(28, 'Antígua e Barbuda', 'ATG'),
(31, 'Azerbaijão', 'AZE'),
(32, 'Argentina', 'ARG'),
(36, 'Austrália', 'AUS'),
(40, 'Áustria', 'AUT'),
(44, 'Bahamas', 'BHS'),
(48, 'Bahrein', 'BHR'),
(50, 'Bangladesh', 'BGD'),
(51, 'Armênia', 'ARM'),
(52, 'Barbados', 'BRB'),
(56, 'Bélgica', 'BEL'),
(60, 'Bermudas', 'BMU'),
(64, 'Butão', 'BTN'),
(68, 'Bolívia', 'BOL'),
(70, 'Bósnia e Herzegovina', 'BIH'),
(72, 'Botsuana', 'BWA'),
(74, 'Ilhas Bouvet', 'BVT'),
(76, 'Brasil', 'BRA'),
(84, 'Belize', 'BLZ'),
(86, 'Território Britânico do Oceano Índico', 'IOT'),
(90, 'Ilhas Salomão', 'SLB'),
(92, 'Ilhas Virgens Britânicas', 'VGB'),
(96, 'Brunei', 'BRN'),
(100, 'Bulgária', 'BGR'),
(104, 'Myanmar', 'MMR'),
(108, 'Burundi', 'BDI'),
(112, 'Bielorrússia', 'BLR'),
(116, 'Camboja', 'KHM'),
(120, 'Camarões', 'CMR'),
(124, 'Canadá', 'CAN'),
(132, 'Cabo Verde', 'CPV'),
(136, 'Ilhas Caiman', 'CYM'),
(140, 'República Centro Africana', 'CAF'),
(144, 'Sri Lanka', 'LKA'),
(148, 'Chade', 'TCD'),
(152, 'Chile', 'CHL'),
(156, 'China', 'CHN'),
(158, 'Republica da China', 'TWN'),
(162, 'Ilhas Natal', 'CXR'),
(166, 'Ilhas Cocos', 'CCK'),
(170, 'Colômbia', 'COL'),
(174, 'Comores', 'COM'),
(175, 'Mayotte', 'MYT'),
(178, 'Congo', 'COG'),
(180, 'República Democrática do Congo', 'COD'),
(184, 'Ilhas Cook', 'COK'),
(188, 'Costa Rica', 'CRI'),
(191, 'Croácia', 'HRV'),
(192, 'Cuba', 'CUB'),
(196, 'Chipre', 'CYP'),
(200, 'Tchecoslováquia', ''),
(203, 'República Tcheca', 'CZE'),
(204, 'Benin', 'BEN'),
(208, 'Dinamarca', 'DNK'),
(212, 'Dominica', 'DMA'),
(214, 'República Dominicana', 'DOM'),
(218, 'Equador', 'ECU'),
(222, 'El Salvador', 'SLV'),
(226, 'Guiné Equatorial', 'GNQ'),
(231, 'Etiópia', 'ETH'),
(232, 'Eritréia', 'ERI'),
(233, 'Estônia', 'EST'),
(234, 'Ilhas Feroe', 'FRO'),
(238, 'Ilhas Malvinas', 'FLK'),
(239, 'Ilhas Geórgia do Sul e Sandwich do Sul', 'SGS'),
(242, 'Fiji', 'FJI'),
(246, 'Finlândia', 'FIN'),
(248, 'Ilhas Åland', 'ALA'),
(250, 'França', 'FRA'),
(254, 'Guiana Francesa', 'GUF'),
(258, 'Polinésia Francesa', 'PYF'),
(260, 'Terras Austrais e Antárticas Francesas', 'ATF'),
(262, 'Djibuti', 'DJI'),
(266, 'Gabão', 'GAB'),
(268, 'Geórgia', 'GEO'),
(270, 'Gâmbia', 'GMB'),
(275, 'Palestina', 'PSE'),
(276, 'Alemanha', 'DEU'),
(288, 'Gana', 'GHA'),
(292, 'Gibraltar', 'GIB'),
(296, 'Quiribati', 'KIR'),
(300, 'Grécia', 'GRC'),
(304, 'Groenlândia', 'GRL'),
(308, 'Granada', 'GRD'),
(312, 'Guadalupe', 'GLP'),
(316, 'Guam', 'GUM'),
(320, 'Guatemala', 'GTM'),
(324, 'Guiné', 'GIN'),
(328, 'Guiana', 'GUY'),
(332, 'Haiti', 'HTI'),
(334, 'Ilha Heard e Ilhas Mcdonald', 'HMD'),
(336, 'Vaticano', 'VAT'),
(339, 'Apátrida1', 'AAA'),
(340, 'Honduras', 'HND'),
(344, 'Hong Kong', 'HKG'),
(348, 'Hungria', 'HUN'),
(352, 'Islândia', 'ISL'),
(356, 'Índia', 'IND'),
(360, 'Indonésia', 'IDN'),
(364, 'Irã', 'IRN'),
(368, 'Iraque', 'IRQ'),
(372, 'Irlanda', 'IRL'),
(376, 'Israel', 'ISR'),
(380, 'Itália', 'ITA'),
(384, 'Costa do Marfim', 'CIV'),
(388, 'Jamaica', 'JAM'),
(392, 'Japão', 'JPN'),
(398, 'Cazaquistão', 'KAZ'),
(400, 'Jordânia', 'JOR'),
(404, 'Quênia', 'KEN'),
(408, 'Coreia do Norte', 'PRK'),
(410, 'Coreia do Sul', 'KOR'),
(414, 'Kuwait', 'KWT'),
(417, 'Quirguistão', 'KGZ'),
(418, 'Laos', 'LAO'),
(422, 'Líbano', 'LBN'),
(426, 'Lesoto', 'LSO'),
(428, 'Letônia', 'LVA'),
(430, 'Libéria', 'LBR'),
(434, 'Líbia', 'LBY'),
(438, 'Liechtenstein', 'LIE'),
(440, 'Lituânia', 'LTU'),
(442, 'Luxemburgo', 'LUX'),
(446, 'Macau', 'MAC'),
(450, 'Madagáscar', 'MDG'),
(454, 'Malawi', 'MWI'),
(458, 'Malásia', 'MYS'),
(462, 'Maldivas', 'MDV'),
(466, 'Mali', 'MLI'),
(470, 'Malta', 'MLT'),
(474, 'Martinica', 'MTQ'),
(478, 'Mauritânia', 'MRT'),
(480, 'Maurício', 'MUS'),
(484, 'México', 'MEX'),
(492, 'Mônaco', 'MCO'),
(496, 'Mongólia', 'MNG'),
(498, 'Moldávia', 'MDA'),
(499, 'Montenegro', 'MNE'),
(500, 'Montserrat', 'MSR'),
(504, 'Marrocos', 'MAR'),
(508, 'Moçambique', 'MOZ'),
(512, 'Oman', 'OMN'),
(516, 'Namíbia', 'NAM'),
(520, 'Nauru', 'NRU'),
(524, 'Nepal', 'NPL'),
(528, 'Holanda', 'NLD'),
(530, 'Antilhas Holandesas', 'ANT'),
(531, 'Curaçao', 'CUW'),
(533, 'Aruba', 'ABW'),
(534, 'Sint Maarten', 'SXM'),
(535, 'Bonaire, Saint Eustatius e Saba', 'BES'),
(540, 'Nova Caledônia', 'NCL'),
(548, 'Vanuatu', 'VUT'),
(554, 'Nova Zelândia', 'NZL'),
(558, 'Nicarágua', 'NIC'),
(562, 'Níger', 'NER'),
(566, 'Nigéria', 'NGA'),
(570, 'Niue', 'NIU'),
(574, 'Ilha Norfolk', 'NFK'),
(578, 'Noruega', 'NOR'),
(580, 'Ilhas Mariana', 'MNP'),
(581, 'Ilhas Menores Distantes dos Estados Unidos', 'UMI'),
(582, 'Ilhas do Pacífico', ''),
(583, 'Micronesia', 'FSM'),
(584, 'Ilhas Marshall', 'MHL'),
(585, 'Palau', 'PLW'),
(586, 'Paquistão', 'PAK'),
(591, 'Panamá', 'PAN'),
(598, 'Papua Nova Guiné', 'PNG'),
(600, 'Paraguai', 'PRY'),
(604, 'Peru', 'PER'),
(608, 'Filipinas', 'PHL'),
(612, 'Pitcairin', 'PCN'),
(616, 'Polônia', 'POL'),
(620, 'Portugal', 'PRT'),
(624, 'Guiné Bissau', 'GNB'),
(626, 'Timor Leste', 'TLS'),
(630, 'Porto Rico', 'PRI'),
(634, 'Catar', 'QAT'),
(638, 'Reunião', 'REU'),
(642, 'Romênia', 'ROU'),
(643, 'Rússia', 'RUS'),
(646, 'Ruanda', 'RWA'),
(652, 'São Bartolomeu', 'BLM'),
(654, 'Santa Helena', 'SHN'),
(659, 'São Cristovão e Nevis', 'KNA'),
(660, 'Anguilla', 'AIA'),
(662, 'Santa Lúcia', 'LCA'),
(663, 'Saint-Martin', 'MAF'),
(666, 'Saint Pierre e Miquelon', 'SPM'),
(670, 'São Vicente e Granadinas', 'VCT'),
(674, 'San Marino', 'SMR'),
(678, 'São Tomé e Príncipe', 'STP'),
(680, 'Sark', ''),
(682, 'Arábia Saudita', 'SAU'),
(686, 'Senegal', 'SEN'),
(688, 'Sérvia', 'SRB'),
(690, 'Seychelles', 'SYC'),
(694, 'Serra Leoa', 'SLE'),
(702, 'Cingapura', 'SGP'),
(703, 'Eslováquia', 'SVK'),
(704, 'Vietnã', 'VNM'),
(705, 'Eslovênia', 'SVN'),
(706, 'Somália', 'SOM'),
(710, 'África do Sul', 'ZAF'),
(716, 'Zimbábue', 'ZWE'),
(724, 'Espanha', 'ESP'),
(728, 'Sudão do Sul', 'SSD'),
(729, 'Sudão', 'SDN'),
(732, 'Saara Ocidental', 'ESH'),
(736, 'Sudão', ''),
(740, 'Suriname', 'SUR'),
(744, 'Svalbard e Jan Mayer', 'SJM'),
(748, 'Suazilândia', 'SWZ'),
(752, 'Suécia', 'SWE'),
(756, 'Suíça', 'CHE'),
(760, 'Síria', 'SYR'),
(762, 'Tajiquistão', 'TJK'),
(764, 'Tailândia', 'THA'),
(768, 'Togo', 'TGO'),
(772, 'Tokelau', 'TKL'),
(776, 'Tonga', 'TON'),
(780, 'Trindade e Tobago', 'TTO'),
(784, 'Emirados Árabes Unidos', 'ARE'),
(788, 'Tunísia', 'TUN'),
(792, 'Turquia', 'TUR'),
(795, 'Turquemenistão', 'TKM'),
(796, 'Ilhas Turks e Caicos', 'TCA'),
(798, 'Tuvalu', 'TUV'),
(800, 'Uganda', 'UGA'),
(804, 'Ucrânia', 'UKR'),
(807, 'República da Macedônia', 'MKD'),
(810, 'União Soviética', ''),
(818, 'Egito', 'EGY'),
(826, 'Reino Unido da Grã Bretanha e Irlanda do Norte', 'GBR'),
(830, 'Ilhas do Canal', ''),
(831, 'Guernsey', 'GGY'),
(832, 'Jersey', 'JEY'),
(833, 'Ilhas de Man', 'IMN'),
(834, 'Tanzânia', 'TZA'),
(840, 'Estados Unidos da América', 'USA'),
(850, 'Ilhas Virgens Americanas', 'VIR'),
(854, 'Burquina Faso', 'BFA'),
(858, 'Uruguai', 'URY'),
(860, 'Uzbequistão', 'UZB'),
(862, 'Venezuela', 'VEN'),
(876, 'Ilhas Wallis e Futuna', 'WLF'),
(882, 'Samoa', 'WSM'),
(887, 'Iémen', 'YEM'),
(890, 'Iugoslávia', ''),
(894, 'Zâmbia', 'ZMB'),
(900, 'Coréia do Norte/Coréia do Sul', ''),
(999, 'Outra Nacionalidade', 'OOO');

UNLOCK TABLES;
