create table `estados` (
  `id` int unsigned not null auto_increment,
  `nome` varchar(255) not null,
  `sigla` char(4) default null,
  `codigo_telefone` varchar(10) default null,
  `pais_id` smallint unsigned not null,
  primary key (`id`),
  constraint `estados_paises_fk` foreign key (`pais_id`) references `paises` (`id`),
  index `estados_nome_idx` (`nome`)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci;


LOCK TABLES `estados` WRITE;

INSERT INTO `estados` VALUES
(11, 'Rondônia', 'RO', NULL, 76),
(12, 'Acre', 'AC', NULL, 76),
(13, 'Amazonas', 'AM', NULL, 76),
(14, 'Roraima', 'RR', NULL, 76),
(15, 'Pará', 'PA', NULL, 76),
(16, 'Amapá', 'AP', NULL, 76),
(17, 'Tocantins', 'TO', NULL, 76),
(21, 'Maranhão', 'MA', NULL, 76),
(22, 'Piauí', 'PI', NULL, 76),
(23, 'Ceará', 'CE', NULL, 76),
(24, 'Rio Grande do Norte', 'RN', NULL, 76),
(25, 'Paraíba', 'PB', NULL, 76),
(26, 'Pernambuco', 'PE', NULL, 76),
(27, 'Alagoas', 'AL', NULL, 76),
(28, 'Sergipe', 'SE', NULL, 76),
(29, 'Bahia', 'BA', NULL, 76),
(31, 'Minas Gerais', 'MG', NULL, 76),
(32, 'Espírito Santo', 'ES', NULL, 76),
(33, 'Rio de Janeiro', 'RJ', NULL, 76),
(35, 'São Paulo', 'SP', NULL, 76),
(41, 'Paraná', 'PR', NULL, 76),
(42, 'Santa Catarina', 'SC', NULL, 76),
(43, 'Rio Grande do Sul', 'RS', NULL, 76),
(50, 'Mato Grosso do Sul', 'MS', NULL, 76),
(51, 'Mato Grosso', 'MT', NULL, 76),
(52, 'Goiás', 'GO', NULL, 76),
(53, 'Distrito Federal', 'DF', NULL, 76),
(54, 'Não Informado', 'NI', NULL, 32),
(55, 'Não Informado', 'NI', NULL, 36),
(56, 'Não Informado', 'NI', NULL, 40),
(57, 'Não Informado', 'NI', NULL, 68),
(58, 'Não Informado', 'NI', NULL, 152),
(59, 'Não Informado', 'NI', NULL, 156),
(60, 'Não Informado', 'NI', NULL, 188),
(61, 'Não Informado', 'NI', NULL, 196),
(62, 'Não Informado', 'NI', NULL, 226),
(63, 'Não Informado', 'NI', NULL, 250),
(64, 'Não Informado', 'NI', NULL, 276),
(65, 'Não Informado', 'NI', NULL, 380),
(66, 'Não Informado', 'NI', NULL, 392),
(67, 'Não Informado', 'NI', NULL, 484),
(68, 'Não Informado', 'NI', NULL, 504),
(69, 'Não Informado', 'NI', NULL, 554),
(70, 'Não Informado', 'NI', NULL, 600),
(71, 'Não Informado', 'NI', NULL, 604),
(72, 'Não Informado', 'NI', NULL, 620),
(73, 'Não Informado', 'NI', NULL, 643),
(74, 'Não Informado', 'NI', NULL, 724),
(75, 'Não Informado', 'NI', NULL, 756),
(76, 'Não Informado', 'NI', NULL, 840),
(77, 'Não Informado', 'NI', NULL, 858),
(78, 'Não Informado', 'NI', NULL, 862);

UNLOCK TABLES;
