services:
  postgres:
    image: postgis/postgis:18-3.6
    container_name: herbario_postgresql_test
    environment:
      POSTGRES_DB: herbario_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - ./test/integration/setup/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    tmpfs:
      - /var/lib/postgresql
