services:
  postgres:
    image: postgis/postgis:18-3.6
    container_name: herbario_postgresql_test
    env_file: .env.test
    environment:
      POSTGRES_DB: $PG_DATABASE
      POSTGRES_USER: $PG_USERNAME
      POSTGRES_PASSWORD: $PG_PASSWORD
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./test/integration/setup/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    tmpfs:
      - /var/lib/postgresql
