services:
  database-backup:
    image: database-backup:local
    container_name: database-backup
    build: .
    environment:
      # PostgreSQL
      DATABASE_HOST:     "${DATABASE_HOST}"
      DATABASE_PORT:     "${DATABASE_PORT}"
      DATABASE_USER:     "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_NAME:     "${DATABASE_NAME}"

      # Google Drive
      GDRIVE_TOKEN:      "${GDRIVE_TOKEN}"
      GDRIVE_FOLDER_ID:  "${GDRIVE_FOLDER_ID}"

      RETENTION_DAILY:   "${RETENTION_DAILY}"
      RETENTION_WEEKLY:  "${RETENTION_WEEKLY}"

      CRON_SCHEDULE:     "${CRON_SCHEDULE}"
      TZ:                "${TZ}"

      # SMTP / Notificações
      SMTP_HOST:         "${SMTP_HOST}"
      SMTP_PORT:         "${SMTP_PORT}"
      SMTP_USER:         "${SMTP_USER}"
      SMTP_PASS:         "${SMTP_PASS}"
      SMTP_FROM:         "${SMTP_FROM}"
      NOTIFY_EMAIL_TO:      "${NOTIFY_EMAIL_TO}"
      NOTIFY_EMAIL_ENABLED: "${NOTIFY_EMAIL_ENABLED}"
